name = "rentcore-board"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[[kv_namespaces]]
binding = "COMMENTS"
id = "80911da4f85f4797981de32630046eba"
